PHONY += all
all:
	gcc -o wait_1 wait_1.c
	gcc -o wait_2 wait_2.c
	gcc -o waitpid_3 waitpid_3.c
	gcc -o waitpid_4 waitpid_4.c

PHONY += clean
clean:
	rm -rf wait_1 wait_2 waitpid_3 waitpid_4

.PHONY: $(PHONY)